### ISSUE TITLE
APIaren emaitzak ez dira orduro eguneratzen

### ISSUE THREAD

**Issue by elacunza** [erral/eitbapi#8]
Hau https://github.com/erral/plugin.video.eitb/issues/3 arazoaren jarraipena da.

Arazoa APIan dagoenez hona aldatu dut.

Orain 2017-04-25ko 20:30ak dira eta hemen ikus dezakegu:
http://www.eitb.tv/eu/get/playlist/5773/
Saioaren 15. atala eskuragarri dagoela.

APIak ordea ez du itzultzen:
http://still-castle-99749.herokuapp.com/playlist/5773

**Comment by elacunza** [comment]
Kodea aztertuta, esango nuke arazoa redis-erako r.set deietan dagoela:
r.set(episode_url, json.dumps(result))

Ez dugu gakoaren iraungitze data zehazten, horrela behar luke (ordu bateko irangitzea izateko)?
r.set(episode_url, json.dumps(result), "ex", "3600")

**Comment by erral** [comment]
ez da ex=3600 bakarrik pasatu behar, defektuzko cachearen politika ere aldatu behar izan dut zerbitzarian, orduarena kontuan hartzeko.

**Comment by elacunza** [comment]
Ederki, milesker!
